name: Build Share Win

# 手动触发
on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '16'  # 适配 electron 3.x

      # 3. 缓存 node_modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. 安装依赖
      - name: Install dependencies
        run: npm install

      # 5. 安装 Wine 支持 cross-build
      - name: Install Wine
        run: sudo apt-get update && sudo apt-get install -y wine

      # 6. 构建 Windows 可执行程序
      - name: Build Windows executable
        run: npm run dist -- --win --x64 --publish never

      # 7. 压缩构建产物
      - name: Zip build output
        run: |
          mkdir -p build_artifacts
          cp dist/*.exe build_artifacts/
          cd build_artifacts
          zip -r Share-Windows.zip *

      # 8. 上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: share-windows
          path: build_artifacts/Share-Windows.zip
